config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  resources :user_subjects
  resources :subjects
  resources :semisters
  resources :courses
  resources :universities
  get '/get_university_courses/:id', to:"semisters#get_university_courses"
  get '/get_course_semisters/:id', to:"subjects#get_course_semisters"
  get 'get_semister_subject_checkbox/:id', to: "welcome#get_semister_subject_checkbox"

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations", unlocks: "users/unlocks"}, path_names: {sign_in: "login", sign_out: "logout", sign_up: "user/registration"}

  authenticated do
    devise_scope :user do
      authenticated :user, ->(u) { u.has_role? :admin } do
        root to: "admin#index", as: :admin_root
      end
      authenticated :user, ->(u) { u.has_role? :student   } do
        root to: "welcome#index", as: :student_root
        put "/update_user_subjects/:id", to: "welcome#update_user_subjects", as: "update_user_subjects"
      end
      authenticated :user, ->(u) { u.has_role? :faculty   } do
        root to: "welcome#index", as: :faculty_root
      end

    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "users/sessions#new", :as => "unauthenticated"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #, :confirmable
  attr_accessor :type
  has_many :user_subjects
  has_many :subjects, :through => :user_subjects
  attr_accessor :university
  attr_accessor :course
  attr_accessor :semister
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def get_semister_subject_checkbox
    @course = Course.where(:id => params[:id].to_i).first
    render :partial => "semister_subjects"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_semister_subjects.html.erb
<%= hidden_field_tag "user[subject_ids][]", nil %>
<% @course.semisters.each do |semister| %>
	<% if semister.subjects.count > 0 %><b><%= semister.year %> Year- <%= semister.semister_name %> Semister</b></br><% end %>
    <% semister.subjects.each do |subject| %>
        <%= check_box_tag "user[subject_ids][]", subject.id, current_user.subjects.collect(&:ids).include?(subject.id) %>
        <%= subject.subject_name %></br>
    <% end %>
<%end%>

app/views/welcome/index.html.erb
  <div class="col-md-1"></div>

  <div class="col-md-4 cwhite">
    <h3 class="pbottom">Select Your Subject</h3>
<%= form_for(current_user, :url => update_user_subjects_path(current_user.id), html: { method: :put }) do |f| %>
    <div class="field col-md-12">
      <div class="col-md-3"><%= f.label :university, :style => "padding-top: 6px;" %></div>
      <div class="col-md-6"><%= f.select :university, University.all.pluck(:university_name,:id), {prompt: "Select University"}, :class => "form-control" %></div>
      
    </div>
    <div class="field col-md-12">&nbsp;</div>
    <div class="field col-md-12">
      <div class="col-md-3"><%= f.label :course, :style => "padding-top: 6px;" %></div>
      <div class="col-md-6"><%= f.select :course, "", {prompt: "Select Course"},:class => "form-control"  %></br></br></div>
    </div>

    <div class="semister_subjects"></div>
    <div class="actions">
      </br></br>
      <%= f.submit "Update", :class => "btn btn-primary btn-lg center-block" %>
    </div>
<% end %>

</div>