config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  resources :user_subjects
  resources :subjects
  resources :semisters
  resources :courses
  resources :universities
  get '/get_university_courses/:id', to:"semisters#get_university_courses"
  get '/get_course_semisters/:id', to:"subjects#get_course_semisters"
  get 'get_semister_subject_checkbox/:id', to: "welcome#get_semister_subject_checkbox"

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations", unlocks: "users/unlocks"}, path_names: {sign_in: "login", sign_out: "logout", sign_up: "user/registration"}

  authenticated do
    devise_scope :user do
      authenticated :user, ->(u) { u.has_role? :admin } do
        root to: "admin#index", as: :admin_root
      end
      authenticated :user, ->(u) { u.has_role? :student   } do
        root to: "welcome#index", as: :student_root
        put "/update_user_subjects/:id", to: "welcome#update_user_subjects", as: "update_user_subjects"
      end
      authenticated :user, ->(u) { u.has_role? :faculty   } do
        root to: "welcome#index", as: :faculty_root
      end

    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "users/sessions#new", :as => "unauthenticated"
    end
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessor :university
  attr_accessor :course
  attr_accessor :semister
  has_many :user_subjects
  has_many :users, :through => :user_subjects
  has_one :semister
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def get_course_semisters
    @semisters = Semister.where(:course_id => params[:id].to_i)
    html = "<option>Select Semister</option>"
    @semisters.each{|semister|
      html << "<option value=#{semister.id}>#{semister.year} Year - #{semister.semister_name  } Semister</option>"
    }
    render :html => html.html_safe
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject_name, :semister_id)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for @subject, :html => { :class => "form-horizontal subject" } do |f| %>

    <% if @subject.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    <div class="control-group">
      <%= f.label :universities, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :university, University.all.pluck(:university_name,:id), {prompt: "Select University"}, { :class => 'form-control'} %>
      </div>

    </div>
    <div class="control-group">
      <%= f.label :courses, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :course, "", {prompt: "Select Course"}, { :class => 'form-control'}  %>
      </div>

    </div>
    <div class="control-group">
      <%= f.label :Semister, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :semister_id, "", {prompt: "Select Semister"} , { :class => 'form-control'} %>
      </div>

    </div>

  <div class="control-group">
    <%= f.label :subject_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject_name, :class => 'form-control' %>
    </div>
    <%= error_span(@subject[:subject_name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            subjects_path, :class => 'btn btn-default' %>

<% end %>

app/views/subjects/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/index.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:subject_name) %></th>
      <th><%= model_class.human_attribute_name(:semister_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= link_to subject.id, subject_path(subject) %></td>
        <td><%= subject.subject_name %></td>
        <td><%= subject.semister_id %></td>
        <td><%=l subject.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subject_path(subject), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subject_path(subject),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %>

app/views/subjects/new.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/show.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:subject_name) %>:</strong></dt>
  <dd><%= @subject.subject_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:semister_id) %>:</strong></dt>
  <dd><%= @subject.semister_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              subjects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subject_path(@subject), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subject_path(@subject),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>