config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  resources :user_subjects
  resources :subjects
  resources :semisters
  resources :courses
  resources :universities
  get '/get_university_courses/:id', to:"semisters#get_university_courses"
  get '/get_course_semisters/:id', to:"subjects#get_course_semisters"
  get 'get_semister_subject_checkbox/:id', to: "welcome#get_semister_subject_checkbox"

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations", unlocks: "users/unlocks"}, path_names: {sign_in: "login", sign_out: "logout", sign_up: "user/registration"}

  authenticated do
    devise_scope :user do
      authenticated :user, ->(u) { u.has_role? :admin } do
        root to: "admin#index", as: :admin_root
      end
      authenticated :user, ->(u) { u.has_role? :student   } do
        root to: "welcome#index", as: :student_root
        put "/update_user_subjects/:id", to: "welcome#update_user_subjects", as: "update_user_subjects"
      end
      authenticated :user, ->(u) { u.has_role? :faculty   } do
        root to: "welcome#index", as: :faculty_root
      end

    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "users/sessions#new", :as => "unauthenticated"
    end
  end

end

app/models/user_subject.rb
class UserSubject < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject
end

app/controllers/user_subjects_controller.rb
class UserSubjectsController < ApplicationController
  before_action :set_user_subject, only: [:show, :edit, :update, :destroy]

  # GET /user_subjects
  # GET /user_subjects.json
  def index
    @user_subjects = UserSubject.all
  end

  # GET /user_subjects/1
  # GET /user_subjects/1.json
  def show
  end

  # GET /user_subjects/new
  def new
    @user_subject = UserSubject.new
  end

  # GET /user_subjects/1/edit
  def edit
  end

  # POST /user_subjects
  # POST /user_subjects.json
  def create
    @user_subject = UserSubject.new(user_subject_params)

    respond_to do |format|
      if @user_subject.save
        format.html { redirect_to @user_subject, notice: 'User subject was successfully created.' }
        format.json { render :show, status: :created, location: @user_subject }
      else
        format.html { render :new }
        format.json { render json: @user_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_subjects/1
  # PATCH/PUT /user_subjects/1.json
  def update
    respond_to do |format|
      if @user_subject.update(user_subject_params)
        format.html { redirect_to @user_subject, notice: 'User subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_subject }
      else
        format.html { render :edit }
        format.json { render json: @user_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_subjects/1
  # DELETE /user_subjects/1.json
  def destroy
    @user_subject.destroy
    respond_to do |format|
      format.html { redirect_to user_subjects_url, notice: 'User subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_subject
      @user_subject = UserSubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_subject_params
      params.require(:user_subject).permit(:user_id, :subject_id)
    end
end

app/helpers/user_subjects_helper.rb
module UserSubjectsHelper
end

app/views/user_subjects/_form.html.erb
<%= form_for(@user_subject) do |f| %>
  <% if @user_subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_subject.errors.count, "error") %> prohibited this user_subject from being saved:</h2>

      <ul>
      <% @user_subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_subjects/edit.html.erb
<h1>Editing User Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_subject %> |
<%= link_to 'Back', user_subjects_path %>

app/views/user_subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Subjects</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_subjects.each do |user_subject| %>
      <tr>
        <td><%= user_subject.user_id %></td>
        <td><%= user_subject.subject_id %></td>
        <td><%= link_to 'Show', user_subject %></td>
        <td><%= link_to 'Edit', edit_user_subject_path(user_subject) %></td>
        <td><%= link_to 'Destroy', user_subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User subject', new_user_subject_path %>

app/views/user_subjects/new.html.erb
<h1>New User Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', user_subjects_path %>

app/views/user_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_subject.user_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @user_subject.subject_id %>
</p>

<%= link_to 'Edit', edit_user_subject_path(@user_subject) %> |
<%= link_to 'Back', user_subjects_path %>