config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  resources :user_subjects
  resources :subjects
  resources :semisters
  resources :courses
  resources :universities
  get '/get_university_courses/:id', to:"semisters#get_university_courses"
  get '/get_course_semisters/:id', to:"subjects#get_course_semisters"
  get 'get_semister_subject_checkbox/:id', to: "welcome#get_semister_subject_checkbox"

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations", unlocks: "users/unlocks"}, path_names: {sign_in: "login", sign_out: "logout", sign_up: "user/registration"}

  authenticated do
    devise_scope :user do
      authenticated :user, ->(u) { u.has_role? :admin } do
        root to: "admin#index", as: :admin_root
      end
      authenticated :user, ->(u) { u.has_role? :student   } do
        root to: "welcome#index", as: :student_root
        put "/update_user_subjects/:id", to: "welcome#update_user_subjects", as: "update_user_subjects"
      end
      authenticated :user, ->(u) { u.has_role? :faculty   } do
        root to: "welcome#index", as: :faculty_root
      end

    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "users/sessions#new", :as => "unauthenticated"
    end
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mess</title>
  <%= stylesheet_link_tag    'application',"storefront", media: 'all'%>
  <%= javascript_include_tag 'application',"scrollIt.min"%>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="nav nav-pills nav-justified">
  <a href= '<%= universities_path%>' class = "btn btn-primary">Universities</a>
  <a href= '<%= courses_path%>' class = "btn btn-primary">Courses</a>
  <a href= '<%= semisters_path%>' class = "btn btn-primary">Semisters</a>
  <a href= '<%= subjects_path%>' class = "btn btn-primary">Subjects</a>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</nav>
<%= yield %>





</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mess</title>
  <%= stylesheet_link_tag    'application',"storefront", media: 'all'%>
  <%= javascript_include_tag 'application',"scrollIt.min"%>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-4 ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle menu-button" data-toggle="collapse" data-target="#myNavbar">
            <span class="glyphicon glyphicon-align-justify"></span>
          </button>
          <a class="navbar-brand logo" href="#">MESS</a>
        </div>
      </div>
      <div class="col-md-8">
        <nav class="collapse navbar-collapse" id="myNavbar" role="navigation">
          <ul class="nav navbar-nav navbar-right menu">
            <li><a href="#page-top" class="page-scroll active">Home</a></li>
            <li><a href="#section2" class="page-scroll">Info</a></li>
            <li><a href="#section4" class="page-scroll">Contact</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>
    <%= yield %>
</body>